### PR TITLE
Update component

### PR DESCRIPTION
**Pull request by cstamas**
Changes:
* update parent (spotless applied as well)
* drop p-c-d
* make it JSR330
* drop plexus XML mumbo jumbo

### CODE REVIEW

**Comment by cstamas** [comment]
Parent lags, spotless does not work with Java 21 and this "experimental" build on 21 cannot be disabled...

**Review by slachiewicz — APPROVED** [review]

**Comment by slachiewicz** [comment]
You can use plexus parent (not a component) that has all fixed. https://github.com/codehaus-plexus/plexus-components/issues/58

We usually separate formatting commit

The experimental build was red for all, thx to this construction only one experiment failed and all others worked. 

Ofc soon I'll remove this one experimental as now spotless works oob.

**Comment by michael-o** [comment]
My big question here is: Is it compatible with Maven 3.8.x? If so, I will need to test it through the entire Doxia 2.0.0 on the weekend, if all works this is a good change and will go into Doxia 2.0.0. So, I need a couple of more days for this.

**Comment by cstamas** [comment]
This change works with any Maven supporting JSR330 (I guess 3.1+? Or 3.2.x?). For sure is not a drop in replacement, as IF there is some Plexus XML config present, it will be ignored (or worse, will explode?)

**Comment by michael-o** [comment]
> This change works with any Maven supporting JSR330 (I guess 3.1+? Or 3.2.x?). For sure is not a drop in replacement, as IF there is some Plexus XML config present, it will be ignored (or worse, will explode?)

Alright, I will test and give you notice...

**Comment by slachiewicz** [comment]
Would it make sense to have it as a separate component or simply inline into in Doxia?

**Comment by cstamas** [comment]
While "site stuff" is the only user of this component, AFAIK is not one single project, but multiple of them. So unsure is it feasible...

**Comment by michael-o** [comment]
> Would it make sense to have it as a separate component or simply inline into in Doxia?

Not on Doxia. Other components use it as well as far as I remember.

**Review by michael-o — CHANGES_REQUESTED** [review]
I tried with Doxia Sitetools:
```
[ERROR] org.apache.maven.doxia.siterenderer.DefaultSiteRendererTest.testRenderExceptionMessageWhenLineNumberIsAvailable -- Time elapsed: 0.664 s <<< ERROR!
org.codehaus.plexus.component.repository.exception.ComponentLookupException:
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.TypeNotPresentException: Type org.codehaus.plexus.velocity.DefaultVelocityComponent not present
  at ClassRealm[plexus.core, parent: null] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.codehaus.plexus.velocity.VelocityComponent
    for field at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.velocity(Unknown Source)
  at ClassRealm[plexus.core, parent: null] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.apache.maven.doxia.siterenderer.DefaultSiteRenderer
  while locating java.lang.Object annotated with *

1 error
      role: org.apache.maven.doxia.siterenderer.SiteRenderer
  roleHint:
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:268)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:256)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:250)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRendererTest.setUp(DefaultSiteRendererTest.java:101)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
```
over and over again. What to do?

**Comment by cstamas** [comment]
Error is right: this PR makes "org.codehaus.plexus.velocity.DefaultVelocityComponent not present" intentional, it moves it to **internal** package. 

You have somewhere plexus XML I guess (as otherwise, with programmatic lookup you'd fail compilation).

**Comment by michael-o** [comment]
I see only:
```java
    @Inject
    private VelocityComponent velocity;
```
in `DefaultSiteRenderer`. I fail to the XML. Can you check what is missing? I am a bit lost. Do we need some shim here?

**Comment by cstamas** [comment]
Something is mentioning `org.codehaus.plexus.velocity.DefaultVelocityComponent` type that is gone, so you need to find that thing. Again, is most probably XML, but may be wrong.

**Review by michael-o — APPROVED** [review]
All issues resolved locally. This deserves 2.1.0-SNAPSHOT bump.

**Pull request merged**
